### PR TITLE
Update Love Rainbows

### PR DESCRIPTION
**Pull request by lindashao1220**
- [x] This pull request follows [Coding  Train Code of Conduct](https://github.com/CodingTrain/Code-of-Conduct)
- [x] This pull request doesn't delete submissions from others.
- [x] This pull request is family friendly and doesn't include any NSFW content.
- [x] I have learned something new about git and GitHub today!

### CODE REVIEW

**Comment by lindashao1220** [comment]
just to express love

**Comment by lindashao1220** [comment]
okok

**Comment by lindashao1220** [comment]
do you agree with me

**Comment by Datt1234** [comment]
Datt123 in log in id but help me in log in

**Pull request closed without merging**
